language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev install
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit -c phpunit.xml
  - phpunit --coverage-text
